### ISSUE TITLE
Possible to add some examples samples to use in a bs project?

### ISSUE THREAD

**Issue by msansen1** [amsross/bs-amqp-connection-manager#2]
Hi,

First, many thanks for your code.
I'm newbie in bs and amqp and I need to use rabbitmq queues in a project. 

Can you add some samples or examples that may help me to implement it in my code?

Or maybe give a project name on GitHub that use it?

Many thanks for your help.

Regards

Mat

**Comment by amsross** [comment]
Hopefully the examples I added in #3 can be of some help to you, @msansen1. Enjoy!
